In [1]:
import numpy as np

In [2]:
a=[12,232]
type(a)

list

In [9]:
b=np.array(a)
b

array([ 12, 232])

In [10]:
type(b)

numpy.ndarray

In [11]:
b.shape

(2,)

In [12]:
b.size

2

In [13]:
b.ndim

1

In [22]:
b=np.zeros((4,2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
b=np.eye(4,5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [38]:
b=np.diag([1,2])
b

array([[1, 0],
       [0, 2]])

In [7]:
a=np.random.randint(1,5,4)

In [8]:
a

array([4, 4, 1, 3])

In [46]:
a=np.random.rand(3,3)
a

array([[0.60158916, 0.0314784 , 0.27502127],
       [0.67899406, 0.52098081, 0.06259369],
       [0.28935154, 0.27290305, 0.6262572 ]])

In [47]:
a=np.random.randn(3,3)
a

array([[-0.38673365, -0.2602736 ,  0.2285526 ],
       [-1.10164978, -0.21293147,  0.86724468],
       [-2.14815629, -1.43662839, -0.57088564]])

In [49]:
np.random.seed(2)
np.random.randint(1,34,23)

array([16,  9, 23, 19, 12,  8, 32, 12, 22, 32, 27, 21,  4,  5,  4,  6, 25,
        5,  7, 32, 20, 32,  3])

In [52]:
a=np.array([23,34,45,56,67,56])
b=a[:]
b[:]=0
a

array([0, 0, 0, 0, 0, 0])

In [56]:
a=np.array([23,34,45,56,67,56])
b=a[:].copy()
b[:]=0
a

array([23, 34, 45, 56, 67, 56])

In [57]:
a=np.arange(12,34,8)
a

array([12, 20, 28])

In [58]:
a.reshape(1,3)

array([[12, 20, 28]])

In [59]:
a.reshape(3,1)

array([[12],
       [20],
       [28]])

In [68]:
a=np.random.randint(1,14,9)
a

array([12,  1, 11,  3,  9, 13, 11,  9,  3])

In [71]:
b=a>6
a[b]

array([12, 11,  9, 13, 11,  9])

In [72]:
b=a<4
a[b]

array([1, 3, 3])

In [73]:
a[a%3==0]

array([12,  3,  9,  9,  3])

In [76]:
a=np.arange(1,5).reshape(2,2)
a
b=np.arange(1,5).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [77]:
a+b

array([[2, 4],
       [6, 8]])

In [78]:
a-b

array([[0, 0],
       [0, 0]])

In [79]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

In [80]:
np.sum(a)

10

In [81]:
np.sum(a,axis=1)

array([3, 7])

In [82]:
a=np.array([12,23,34,2,12,3,23,2,312,2,323,23,23])
a


array([ 12,  23,  34,   2,  12,   3,  23,   2, 312,   2, 323,  23,  23])

In [83]:
np.unique(a)

array([  2,   3,  12,  23,  34, 312, 323])

In [84]:
np.unique(a,return_index=True,return_counts= True)

(array([  2,   3,  12,  23,  34, 312, 323]),
 array([ 3,  5,  0,  1,  2,  8, 10], dtype=int64),
 array([3, 1, 2, 4, 1, 1, 1], dtype=int64))

In [85]:
a=np.linspace(1,4,9)

In [86]:
a

array([1.   , 1.375, 1.75 , 2.125, 2.5  , 2.875, 3.25 , 3.625, 4.   ])

In [87]:
a=np.arange(1,5)
b=np.arange(6,10)
np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

In [88]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])