In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('C:\\Users\\asd\\Downloads\\covid_toy.csv')

In [3]:
df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

## colunm transformer

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train , x_test , y_train , y_test= train_test_split(df.drop(
columns =['has_covid']),df['has_covid'],test_size= 0.2)


## Manually type output

In [7]:
from sklearn.impute import SimpleImputer

In [8]:
si = SimpleImputer(strategy = 'mean')
x_train_fever = si.fit_transform(x_train[['fever']])

x_test_fever = si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [9]:
from sklearn.preprocessing import OrdinalEncoder


In [10]:
# Ordinal Encoding ---->cough

oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

#also test data
x_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [11]:
from sklearn.preprocessing import OneHotEncoder


In [12]:

# OneHotEncoding --> Gender, city
ohe = OneHotEncoder (drop = 'first', sparse_output = False )
x_train_gender_city= ohe.fit_transform(x_train [['gender', 'city']])

# also the test data
x_test_gender_city=ohe.fit_transform(x_test[['gender', 'city']])
x_train_gender_city.shape


(80, 4)

In [13]:
#Extracting Age
x_train_age = x_train.drop(columns =
['gender', 'fever', 'cough', 'city']).values
# also the test data
x_test_age= x_test.drop(columns=['gender', 'fever', 'cough', 'city']).values
x_train_age.shape


(80, 1)

In [14]:
x_train_transformed =np.concatenate((x_train_age, x_train_fever,
                                    x_train_gender_city,
                                    x_train_cough), axis=1)

In [15]:
x_train_transformed.shape

(80, 7)

## by the help of column transformer

In [16]:

from sklearn.compose import ColumnTransformer
transformer= ColumnTransformer (transformers=[
#
#
# this is how to import Column Transformer
('tnf1', SimpleImputer(), ['fever']), # in a 'fever'column by the help of SI we
# fill missing values by mean, median mode.

('tnf2', OrdinalEncoder(categories = [['Mild', 'Strong']]), ['cough']), #by this process
# we encode our data.
('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city']) ],
                                remainder='passthrough')
# remainder = passthrough ==>
#it means rest all the columns remain some

In [17]:
transformer.fit_transform(x_train).shape

(80, 7)

In [18]:
transformer.transform(x_test).shape

(20, 7)

## The Function Transformer is a tool in scikit-learn, a popular Python library for machine learning, that allows you to apply a specified function to the input data. The Function Transformer can be useful for performing custom transformations of input data in a machine learning pipeline.


In [20]:
from math import log
from sklearn.preprocessing import FunctionTransformer

#create a dataset
x=np.array([[1,2],[3,4]])

#define the transformation function
log_transform = FunctionTransformer(np.log1p)

#apply the transformation to the dataset
x_transformed= log_transform.transform(x)

#print the transformed dataset
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [22]:
from sklearn.preprocessing import FunctionTransformer

#create a dataset
x=np.array([[1,2],[3,4]])

#define the custome feature engineering function
def asd(x):
    return np.hstack((x,x**2))

# create a function transformer to apply custom function
custom_transformer =FunctionTransformer(asd)


#apply the transformation to the dataset
x_transformed= custom_transformer.transform(x)

#print the transformed dataset
print(x_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [24]:
from sklearn.preprocessing import FunctionTransformer

#create a dataset
x=np.array([[1,2],[3,4]])

#define the custome feature engineering function
def my_scaling(x):
    return x/ np.max(x)

# create a function transformer to apply custom function
custom_transformer =FunctionTransformer(my_scaling)


#apply the transformation to the dataset
x_transformed= custom_transformer.transform(x)

#print the transformed dataset
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [26]:
from sklearn.preprocessing import FunctionTransformer

#create a dataset
x=np.array([[1,2],[3,np.nan]])

#define the custome feature engineering function
def my_cleaning(x):
    
    x[np.isnan(x)]=0
    return x

# create a function transformer to apply custom function
custom_transformer =FunctionTransformer(my_cleaning)


#apply the transformation to the dataset
x_transformed= custom_transformer.transform(x)

#print the transformed dataset
print(x_transformed)

[[1. 2.]
 [3. 0.]]


In [ ]:
df=pd.read_csv('C:\\Users\\asd\\Downloads\\placement.csv')

In [ ]:
df.head(3)

In [ ]:
x= df.drop(columns= ['placed'])
y= df['placed']

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform = FunctionTransformer(np.log1p)

#apply the transformation to the dataset
x_transformed = log_transform.transform(x)