In [1]:
import numpy as np

## view vs copy

In [2]:
a=np.array([10,20,30,40,50,60,70,80])   ## view means modification in orignal data
b=a[2:5]
b[:]=0
a

array([10, 20,  0,  0,  0, 60, 70, 80])

In [3]:
a=np.array([10,20,30,40,50,60,70,80])   ## copy() means modification in duplicate file
b=a[2:5].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

## Reshaping the data

In [4]:
# # we know that 
# n(rows)*n(column)= n(total_elements)
# if we have total element =12
# 1*12,12*1
# 2*6,6*2
# 3*4,4*3



In [5]:
a=np.random.randint(1,50,12)
a

array([46, 20, 35, 36, 13,  6, 10,  1,  9, 48,  1,  9])

In [6]:
a.reshape(6,2)

array([[46, 20],
       [35, 36],
       [13,  6],
       [10,  1],
       [ 9, 48],
       [ 1,  9]])

In [7]:
a.reshape(2,6)

array([[46, 20, 35, 36, 13,  6],
       [10,  1,  9, 48,  1,  9]])

In [8]:
a.reshape(4,3)

array([[46, 20, 35],
       [36, 13,  6],
       [10,  1,  9],
       [48,  1,  9]])

In [9]:
a.reshape(3,4)

array([[46, 20, 35, 36],
       [13,  6, 10,  1],
       [ 9, 48,  1,  9]])

In [10]:
a=np.random.randint(1,100,72)
a

array([62, 97, 44, 38, 86, 93, 82, 47, 44, 46, 14, 68, 26, 38,  1, 63, 50,
       34, 26,  4, 11, 79, 84, 91, 25, 69, 22, 24, 73, 78,  5,  1, 98, 11,
       98, 68, 20, 97, 44, 61, 94, 58, 70, 79, 54, 27, 51, 36, 54, 16, 86,
       80, 70, 70, 26, 25, 14, 69, 77, 87, 15, 36, 31, 89, 16, 57, 71, 42,
       55, 63,  9, 53])

In [11]:
a.reshape(1,72)

array([[62, 97, 44, 38, 86, 93, 82, 47, 44, 46, 14, 68, 26, 38,  1, 63,
        50, 34, 26,  4, 11, 79, 84, 91, 25, 69, 22, 24, 73, 78,  5,  1,
        98, 11, 98, 68, 20, 97, 44, 61, 94, 58, 70, 79, 54, 27, 51, 36,
        54, 16, 86, 80, 70, 70, 26, 25, 14, 69, 77, 87, 15, 36, 31, 89,
        16, 57, 71, 42, 55, 63,  9, 53]])

In [13]:
a.reshape(72,1)

array([[62],
       [97],
       [44],
       [38],
       [86],
       [93],
       [82],
       [47],
       [44],
       [46],
       [14],
       [68],
       [26],
       [38],
       [ 1],
       [63],
       [50],
       [34],
       [26],
       [ 4],
       [11],
       [79],
       [84],
       [91],
       [25],
       [69],
       [22],
       [24],
       [73],
       [78],
       [ 5],
       [ 1],
       [98],
       [11],
       [98],
       [68],
       [20],
       [97],
       [44],
       [61],
       [94],
       [58],
       [70],
       [79],
       [54],
       [27],
       [51],
       [36],
       [54],
       [16],
       [86],
       [80],
       [70],
       [70],
       [26],
       [25],
       [14],
       [69],
       [77],
       [87],
       [15],
       [36],
       [31],
       [89],
       [16],
       [57],
       [71],
       [42],
       [55],
       [63],
       [ 9],
       [53]])

In [14]:
a.reshape(2,36)

array([[62, 97, 44, 38, 86, 93, 82, 47, 44, 46, 14, 68, 26, 38,  1, 63,
        50, 34, 26,  4, 11, 79, 84, 91, 25, 69, 22, 24, 73, 78,  5,  1,
        98, 11, 98, 68],
       [20, 97, 44, 61, 94, 58, 70, 79, 54, 27, 51, 36, 54, 16, 86, 80,
        70, 70, 26, 25, 14, 69, 77, 87, 15, 36, 31, 89, 16, 57, 71, 42,
        55, 63,  9, 53]])

In [15]:
a.reshape(36,2)

array([[62, 97],
       [44, 38],
       [86, 93],
       [82, 47],
       [44, 46],
       [14, 68],
       [26, 38],
       [ 1, 63],
       [50, 34],
       [26,  4],
       [11, 79],
       [84, 91],
       [25, 69],
       [22, 24],
       [73, 78],
       [ 5,  1],
       [98, 11],
       [98, 68],
       [20, 97],
       [44, 61],
       [94, 58],
       [70, 79],
       [54, 27],
       [51, 36],
       [54, 16],
       [86, 80],
       [70, 70],
       [26, 25],
       [14, 69],
       [77, 87],
       [15, 36],
       [31, 89],
       [16, 57],
       [71, 42],
       [55, 63],
       [ 9, 53]])

In [16]:
a.reshape(3,24)

array([[62, 97, 44, 38, 86, 93, 82, 47, 44, 46, 14, 68, 26, 38,  1, 63,
        50, 34, 26,  4, 11, 79, 84, 91],
       [25, 69, 22, 24, 73, 78,  5,  1, 98, 11, 98, 68, 20, 97, 44, 61,
        94, 58, 70, 79, 54, 27, 51, 36],
       [54, 16, 86, 80, 70, 70, 26, 25, 14, 69, 77, 87, 15, 36, 31, 89,
        16, 57, 71, 42, 55, 63,  9, 53]])

In [17]:
a.reshape(24,3)

array([[62, 97, 44],
       [38, 86, 93],
       [82, 47, 44],
       [46, 14, 68],
       [26, 38,  1],
       [63, 50, 34],
       [26,  4, 11],
       [79, 84, 91],
       [25, 69, 22],
       [24, 73, 78],
       [ 5,  1, 98],
       [11, 98, 68],
       [20, 97, 44],
       [61, 94, 58],
       [70, 79, 54],
       [27, 51, 36],
       [54, 16, 86],
       [80, 70, 70],
       [26, 25, 14],
       [69, 77, 87],
       [15, 36, 31],
       [89, 16, 57],
       [71, 42, 55],
       [63,  9, 53]])

In [19]:
a.reshape(4,18)

array([[62, 97, 44, 38, 86, 93, 82, 47, 44, 46, 14, 68, 26, 38,  1, 63,
        50, 34],
       [26,  4, 11, 79, 84, 91, 25, 69, 22, 24, 73, 78,  5,  1, 98, 11,
        98, 68],
       [20, 97, 44, 61, 94, 58, 70, 79, 54, 27, 51, 36, 54, 16, 86, 80,
        70, 70],
       [26, 25, 14, 69, 77, 87, 15, 36, 31, 89, 16, 57, 71, 42, 55, 63,
         9, 53]])

In [20]:
a.reshape(18,4)

array([[62, 97, 44, 38],
       [86, 93, 82, 47],
       [44, 46, 14, 68],
       [26, 38,  1, 63],
       [50, 34, 26,  4],
       [11, 79, 84, 91],
       [25, 69, 22, 24],
       [73, 78,  5,  1],
       [98, 11, 98, 68],
       [20, 97, 44, 61],
       [94, 58, 70, 79],
       [54, 27, 51, 36],
       [54, 16, 86, 80],
       [70, 70, 26, 25],
       [14, 69, 77, 87],
       [15, 36, 31, 89],
       [16, 57, 71, 42],
       [55, 63,  9, 53]])

In [21]:
a.reshape(6,12)

array([[62, 97, 44, 38, 86, 93, 82, 47, 44, 46, 14, 68],
       [26, 38,  1, 63, 50, 34, 26,  4, 11, 79, 84, 91],
       [25, 69, 22, 24, 73, 78,  5,  1, 98, 11, 98, 68],
       [20, 97, 44, 61, 94, 58, 70, 79, 54, 27, 51, 36],
       [54, 16, 86, 80, 70, 70, 26, 25, 14, 69, 77, 87],
       [15, 36, 31, 89, 16, 57, 71, 42, 55, 63,  9, 53]])

In [22]:
a.reshape(12,6)

array([[62, 97, 44, 38, 86, 93],
       [82, 47, 44, 46, 14, 68],
       [26, 38,  1, 63, 50, 34],
       [26,  4, 11, 79, 84, 91],
       [25, 69, 22, 24, 73, 78],
       [ 5,  1, 98, 11, 98, 68],
       [20, 97, 44, 61, 94, 58],
       [70, 79, 54, 27, 51, 36],
       [54, 16, 86, 80, 70, 70],
       [26, 25, 14, 69, 77, 87],
       [15, 36, 31, 89, 16, 57],
       [71, 42, 55, 63,  9, 53]])

## conditional selection in Numpy

In [24]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
a>12

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True])

In [26]:
a<12

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False])

In [28]:
b=a>12
a[b]

array([13, 14, 15])

In [30]:
c=a<12
a[c]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [32]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [33]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [34]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [35]:
a+b

array([[ 6,  8],
       [10, 12]])

In [36]:
a-b

array([[-4, -4],
       [-4, -4]])

In [38]:
a*b   ## wrong method

array([[ 5, 12],
       [21, 32]])

In [39]:
a.dot(b) #right 

array([[19, 22],
       [43, 50]])

In [41]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.sum(a)

45

In [43]:
np.sum(a,axis=1) ## Row wise sum

array([ 6, 15, 24])

In [45]:
np.sum(a,axis=0)  ## column wise sum

array([12, 15, 18])

In [46]:
# unique() ===> it will return unique values or eliminate duplicate values
# it will return three array
# 1. unique values array
# 2. indexing of orignal value
# 3. returns frequency of each unique value

In [47]:
a=np.array([1,2,3,2,1,3,4,5,6,4,3,2,2,2])
a

array([1, 2, 3, 2, 1, 3, 4, 5, 6, 4, 3, 2, 2, 2])

In [54]:
np.unique(a, return_index=True,return_counts= True)

(array([1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 6, 7, 8], dtype=int64),
 array([2, 5, 3, 2, 1, 1], dtype=int64))

In [55]:
# Linspace() ===> It will create an array in which difference of each  value will be equal


In [56]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

## stacking in numpy


In [57]:
# stacking in numpy
# 1. hstack()===> It will combined multiple arrays into horizontally


In [58]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)

In [60]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
# 2. vstack() ===> it will combined multiple array into vertically

In [62]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])