In [1]:
# numpy ===> numpy is an open source lirary that is used for scietific calculation

In [2]:
# why we use numpy whenever we have list?
# 1. Hompgeneous data type
# 2. memory less cosume
# 3. less time consume

In [3]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np

In [5]:
a=[12,23,34]
type(a)

list

In [6]:
b=np.array(a)
print(b)
print(type(b))

[12 23 34]
<class 'numpy.ndarray'>


In [7]:
# # Dimesion ===>
# 1-D ===> element exists in x- direction
# 2-D ===> element exists in x and y direction
# 3-D ===> element exists in x,y,z direction

In [8]:
print("total shape:",b.shape)

total shape: (3,)


In [9]:
print("Total element:",b.size)  #size= n(rows) * n(column)

Total element: 3


In [10]:
print("total Dimension:",b.ndim)  # ndim is reffer to dimension of array

total Dimension: 1


In [11]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
b=np.array(a)
print(b)
b.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [13]:
print("total shape:",b.shape)
print("Total element:",b.size)  #size= n(rows) * n(column)
print("total Dimension:",b.ndim)  # ndim is reffer to dimension of array

total shape: (3, 3)
Total element: 9
total Dimension: 2


## create a user defined array

In [14]:
a=[]
size=int(input("enter size: "))
for i in range(size):
    val=int(input("enter value "))
    a.append(val)
b=np.array(a)
b

enter size: 4
enter value 3
enter value 23
enter value 12
enter value 12


array([ 3, 23, 12, 12])

## Numpy  functions

In [15]:
# # image==> pixels(0-255)px ==> opx(white) ==> normalize==> (0-1)px

# # (a). black and white image ==> hight, width
# # (B). colourful image ==> height, width, coloe_channel(red,green,blue)

# # #matrix ===> n(rows) = n(columns) ==> symmatric matrix , n(r)!= n(c) ==> Asymmatric matrix

# # random number generator ==> random module
# # data science==> simple line equation= y=mx+b  #3 (x,y)= co-ordinates, m=weigth, b=intercept

# matrix => row,column
# matrix= digonal positional element =[(1,1),(2,2,),(3,3),...,(n,n)]


## 1. zeros(). => it will create an array in hich all the values are 0


In [16]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [17]:
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

## 2. ones(). => it will create an array in which all the values are 1.

In [18]:
a=np.ones(3)
a

array([1., 1., 1.])

In [19]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
a.shape

(2, 3)

## 3. eye(). => it will create an array in which digonal positional element are 1 and rest all are 0.

In [21]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 4. diag()  => it will create an array in which we can customize our diagonal positional elements 

In [23]:
a=np.diag([1,23,34,45])
a

array([[ 1,  0,  0,  0],
       [ 0, 23,  0,  0],
       [ 0,  0, 34,  0],
       [ 0,  0,  0, 45]])

## random module

In [24]:
#  random module
# 1. otp generation
# 2. dataset => 1 dumy column add
# 3. rando;y weights initialize

In [25]:
# 1. randint( min_num,max_num, total_num)

In [26]:
a=np.random.randint(1,10,4)
a

array([8, 5, 6, 5])

In [27]:
# 2. rand(total_num) => it will return numbers from 0 to 1


In [28]:
a=np.random.rand(5)
a

array([0.87025129, 0.85004328, 0.83263681, 0.04323869, 0.83384669])

In [29]:
# 3. randn() ==> -3 to 3


In [30]:
a=np.random.randn(5)
a

array([-0.49612615, -0.2458543 , -1.33424675,  0.94433106, -0.49443364])

In [31]:
# 4. seed() ==> it will fix our data once the data has been generated

In [32]:
np.random.seed(2)
a=np.random.randint(1,10,4)
a

array([9, 9, 7, 3])